sudo: required

language: bash

cache:
  directories:
  - composer/cache

git:
  depth: 1

services:
  - docker
  - docker-compose

before_install:
  - 'chmod +x ./travis_install.sh'
  - 'travis_retry docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}'

install:
  - './travis_install.sh'
  - 'docker-compose -f ./docker/docker-compose.yml up -d'
  - 'docker exec turbo-erp-api-php-fpm sh -c "composer install --no-progress --no-suggest"'

before_script:
  - 'docker exec turbo-erp-api-php-fpm sh -c "php artisan migrate -n"'
  - 'docker exec turbo-erp-mysql-dev sh -c "mysql -e \"CREATE DATABASE IF NOT EXISTS codeception_test\""'
  - 'docker exec turbo-erp-mysql-dev sh -c "mysqldump --no-data turbo_erp | mysql -D codeception_test"'

script:
  - 'docker exec turbo-erp-api-php-fpm sh -c "vendor/bin/codecept run unit,integration,api --steps --coverage --coverage-xml"'
