version: '3'

services:
  turbo-erp-api-nginx:
    image: nginx:alpine
    container_name: turbo-erp-api-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d # sites-enabled
      - ..:/var/www/project # root folder
    ports:
      - 40080:80
    links:
      - turbo-erp-api-php-fpm

  turbo-erp-api-mysql:
      image: mysql:latest
      container_name: turbo-erp-api-mysql
      ports:
        - 43306:3306
      volumes:
        - ./mysql/data:/docker-entrypoint-initdb.d
      environment:
        MYSQL_DATABASE: turbo_erp
        MYSQL_ROOT_PASSWORD: root

  turbo-erp-api-php-fpm:
    image: turboranger/php-fpm
    container_name: turbo-erp-api-php-fpm
    volumes:
      - ..:/var/www/project # root folder
      - ./php-fpm:/usr/local/etc/php/conf.d.user
      - ../composer:/root/composer
    links:
      - turbo-erp-api-mysql
    environment:
      IN_DOCKER: 1
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_HOME: /root/composer
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d.user
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=192.168.0.110 remote_port=9000 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=turbo-erp-api-php-fpm"

  turbo-erp-api-selenium:
    image: selenium/standalone-chrome:latest
    container_name: turbo-erp-api-selenium

  turbo-erp-api-pma:
    image: phpmyadmin/phpmyadmin
    container_name: turbo-erp-api-pma
    links:
      - turbo-erp-api-mysql
    ports:
      - 48183:80
    environment:
      PMA_HOST: turbo-erp-api-mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1