version: '3'

services:
  turbo-erp-api-nginx:
    image: nginx:alpine
    restart: always
    container_name: turbo-erp-api-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d # sites-enabled
      - ..:/var/www/project # root folder
    ports:
      - 40080:80
    links:
      - turbo-erp-api-php-fpm

  turbo-erp-mysql-dev:
      image: turboranger/turbo-erp-mysql-dev
      restart: always
      container_name: turbo-erp-mysql-dev
      ports:
        - 43306:3306

  turbo-erp-api-php-fpm:
    image: turboranger/php-fpm
    restart: always
    container_name: turbo-erp-api-php-fpm
    volumes:
      - ..:/var/www/project # root folder
      - ./php-fpm:/usr/local/etc/php/conf.d.user
      - ../composer:/root/composer
    links:
      - turbo-erp-mysql-dev
    environment:
      IN_DOCKER: 1
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_HOME: /root/composer
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d.user
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=192.168.1.3 remote_port=9000 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=turbo-erp-api-php-fpm"

  turbo-erp-api-selenium:
    image: selenium/standalone-chrome:latest
    container_name: turbo-erp-api-selenium

  turbo-erp-api-pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: turbo-erp-api-pma
    links:
      - turbo-erp-mysql-dev
    ports:
      - 48183:80
    environment:
      PMA_HOST: turbo-erp-mysql-dev
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
